name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore cached Docker image
      id: cache-docker
      uses: actions/cache@v4
      with:
        path: image.tar
        key: ${{ runner.os }}-docker-buec440-pintos-latest

    - name: Load Docker image from cache (if available)
      if: steps.cache-docker.outputs.cache-hit == 'true'
      run: docker load -i image.tar

    - name: Pull and save Docker image (if not cached)
      if: steps.cache-docker.outputs.cache-hit != 'true'
      run: |
        docker pull buec440/pintos:latest
        docker save buec440/pintos:latest -o image.tar

    - name: Set up directory on runner
      run: |
        mkdir pintos
        mv src pintos/
        mv setup.sh pintos/
        mv README.md pintos/

    - name: Compile and Run Pintos
      run: |
        docker run \
          --rm \
          -e BXSHARE='/home/BUOS/toolchain/x86_64/share/bochs' \
          --mount type=bind,source="$(pwd)/pintos",target=/home/BUOS/pintos \
          buec440/pintos:latest \
          /bin/bash -c " \
            cd /home/BUOS/pintos && \
            source setup.sh && \
            cd src/threads && \
            make clean && \
            make \
          "
