name: Pintos CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  # Step 1: Ensure image exists in GHCR
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image exists in GHCR
        id: check
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository_owner }}/pintos:latest > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Pull from Docker Hub and push to GHCR (if missing)
        if: steps.check.outputs.exists == 'false'
        run: |
          docker pull buec440/pintos:latest
          docker tag buec440/pintos:latest ghcr.io/${{ github.repository_owner }}/pintos:latest
          docker push ghcr.io/${{ github.repository_owner }}/pintos:latest

  # Step 2: Build and run using GHCR image
  build:
    runs-on: ubuntu-latest
    needs: mirror   # wait for mirror job
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up directory on runner
        run: |
          mkdir pintos
          mv src pintos/
          mv setup.sh pintos/
          mv README.md pintos/

      - name: Compile and Run Pintos
        run: |
          docker run \
            --rm \
            -e BXSHARE='/home/BUOS/toolchain/x86_64/share/bochs' \
            --mount type=bind,source="$(pwd)/pintos",target=/home/BUOS/pintos \
            ghcr.io/${{ github.repository_owner }}/pintos:latest \
            /bin/bash -c " \
              cd /home/BUOS/pintos && \
              source setup.sh && \
              cd src/threads && \
              make clean && \
              make \
            "

